// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2PA7xGn1Velh5GkxMYeyvRoaQtmvwg_8',
    appId: '1:14817130997:web:569269b8a264b2e7d408bc',
    messagingSenderId: '14817130997',
    projectId: 'zaha-8793f',
    authDomain: 'zaha-8793f.firebaseapp.com',
    storageBucket: 'zaha-8793f.appspot.com',
    measurementId: 'G-4ZHPQ1R8T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL50Zd-RdTjyttvO3Mzy32wbKD7H4bB34',
    appId: '1:14817130997:android:3071e93ea506ab6dd408bc',
    messagingSenderId: '14817130997',
    projectId: 'zaha-8793f',
    storageBucket: 'zaha-8793f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3K3HH_M2oT2oppkg4l5r2UaK86IYqJGI',
    appId: '1:14817130997:ios:73d07e51e574f5f1d408bc',
    messagingSenderId: '14817130997',
    projectId: 'zaha-8793f',
    storageBucket: 'zaha-8793f.appspot.com',
    iosBundleId: 'com.example.zaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3K3HH_M2oT2oppkg4l5r2UaK86IYqJGI',
    appId: '1:14817130997:ios:73d07e51e574f5f1d408bc',
    messagingSenderId: '14817130997',
    projectId: 'zaha-8793f',
    storageBucket: 'zaha-8793f.appspot.com',
    iosBundleId: 'com.example.zaha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2PA7xGn1Velh5GkxMYeyvRoaQtmvwg_8',
    appId: '1:14817130997:web:ca42b00490975603d408bc',
    messagingSenderId: '14817130997',
    projectId: 'zaha-8793f',
    authDomain: 'zaha-8793f.firebaseapp.com',
    storageBucket: 'zaha-8793f.appspot.com',
    measurementId: 'G-CQGB0M73ZQ',
  );
}
